In [36]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error

In [37]:
data = pd.read_csv("C:\\Users\\Aravinthan\\Desktop\\MLO\\data\\Boston.CSV")

In [38]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio   black  lstat  medv
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7  396.90   5.33  36.2

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [40]:
model1 = LinearRegression()
model2 = Ridge(alpha=1)
model3 = Lasso(alpha=1)
model4 = ElasticNet(alpha=1)

In [41]:
model1.fit(x_train, y_train)
model2.fit(x_train, y_train)
model3.fit(x_train, y_train)
model4.fit(x_train, y_train)

ElasticNet(alpha=1)

In [42]:
model1.coef_

array([-1.25156811e-01,  4.48575121e-02,  2.01265385e-02, -1.62895522e+01,
        3.77366409e+00, -2.13185120e-03, -1.40611846e+00,  2.66835482e-01,
       -1.21692284e-02, -1.07660161e+00,  8.72533635e-03, -4.94425348e-01])

In [43]:
model2.coef_

array([-0.12233832,  0.04609301, -0.0098171 , -8.64343893,  3.81854443,
       -0.00952306, -1.29823342,  0.24385986, -0.01267859, -0.99836523,
        0.00913742, -0.50051639])

In [44]:
model3.coef_

array([-0.05889028,  0.05317657, -0.        , -0.        ,  0.67954962,
        0.01684077, -0.6487664 ,  0.198738  , -0.01399421, -0.86421958,
        0.00660309, -0.73120957])

In [45]:
model4.coef_

array([-0.07922321,  0.05637835, -0.02484651, -0.        ,  0.84270351,
        0.01551814, -0.75788431,  0.22869565, -0.01471232, -0.85689217,
        0.00690502, -0.71471227])

In [46]:
y_predict1 = model1.predict(x_test)
y_predict2 = model2.predict(x_test)
y_predict3 = model3.predict(x_test)
y_predict4 = model4.predict(x_test)

In [47]:
print(np.sqrt(mean_squared_error(y_test,y_predict1)))
print(np.sqrt(mean_squared_error(y_test,y_predict2)))
print(np.sqrt(mean_squared_error(y_test,y_predict3)))
print(np.sqrt(mean_squared_error(y_test,y_predict4)))

5.849124083786667
5.905162730945172
6.457561211475197
6.376937515586476


In [48]:
##KFold technique

In [49]:
data = pd.read_csv("C:\\Users\\Aravinthan\\Desktop\\MLO\\data\\Boston.CSV")

In [50]:
data.head()

crim    zn  indus    nox     rm   age     dis  rad  tax  ptratio   black  lstat  medv
0  0.00632  18.0   2.31  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18  0.458  7.147  54.2  6.0622    3  222     18.7  396.90   5.33  36.2

In [31]:
x = data.iloc[:,:12].values
y = data.iloc[:,12].values

In [32]:
kf = KFold(n_splits=5)

In [33]:
model = LinearRegression()

In [34]:
list(kf.split(data))

[(array([102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
         115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
         128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
         141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166,
         167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
         180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192,
         193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
         206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218,
         219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231,
         232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244,
         245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257,
         258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270,
         271, 272, 273, 274, 275, 276,

In [51]:
x = data.iloc[:,:12].values
y = data.iloc[:,12].values

In [56]:
RMSE = []

for fold in list(kf.split(data)):
    model.fit(x[fold[0],:], y[fold[0]])
    y_pred = model.predict(x[fold[1],:])
    RMSE.append(np.sqrt(mean_squared_error(y_pred, y[fold[1]])))

print(RMSE)

[np.float64(3.5597962719153933), np.float64(4.927922755053224), np.float64(5.27624637707923), np.float64(9.060074446891234), np.float64(6.041967770846661)]


In [57]:
cvals = -cross_val_score(model,x,y,cv=10,scoring="neg_mean_squared_error")

In [58]:
cvals = np.sqrt(cvals)
cvals

array([ 3.02821185,  3.84212047,  3.43361152,  5.91030359,  5.18509234,
        4.41907104,  3.271935  , 13.09534082,  5.92386853,  3.41286658])